name: Build image for KeepItTextBot

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (leave empty for timestamp)'
        required: false
        type: string

env:
  SERVICE_NAME: keep-it-text-bot
  DOCKER_USERNAME: aondas

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Generate version if not provided
        id: version
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            VERSION=$(date +"%Y%m%d-%H%M%S")
          else
            VERSION="${{ inputs.version }}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./${{ env.SERVICE_NAME }}
          file: ./${{ env.SERVICE_NAME }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:latest

      - name: Summary
        run: |
          echo "${{ env.SERVICE_NAME }} image is built!"
          echo "Image: ${{ env.DOCKER_USERNAME }}/${{ env.SERVICE_NAME }}:${{ steps.version.outputs.version }}"
          echo "Go to Railway and redeploy your service"